# Generated by Django 6.0.7 on 2026-07-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('token_expired', 'Token Expired'), ('sync_error', 'Sync Error'), ('name_mismatch', 'Name Mismatch'), ('enterprise_inactive', 'Enterprise Inactive')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='enterprises.enterprise')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('kind', 'enterprise')},
            },
        ),
    ]
