# Generated by Django 6.0.7 on 2026-07-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_recipient_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('token_expired', 'Token Expired'), ('sync_error', 'Sync Error'), ('name_mismatch', 'Name Mismatch'), ('enterprise_inactive', 'Enterprise Inactive'), ('force_assigned', 'Force Assigned')], max_length=30),
        ),
    ]
