# Generated by Django 6.0.7 on 2026-07-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=300)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['path', 'timestamp'], name='admin_tools_path_f572eb_idx')],
            },
        ),
    ]
