# Generated by Django 6.0.6 on 2026-07-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('team', models.CharField(choices=[('ST', 'ST'), ('EVE', 'EVE'), ('PLATFORM', 'PLATFORM')], max_length=20)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('team_member', 'Team Member')], default='team_member', max_length=20)),
            ],
        ),
    ]
