# Generated by Django 6.0.6 on 2026-07-10 07:29

from django.db import migrations, models


_INITIAL_TEAMS = ['EVE', 'PLATFORM', 'ST']


def seed_teams(apps, schema_editor):
    Team = apps.get_model('users', 'Team')
    for name in _INITIAL_TEAMS:
        Team.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_teams, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='portaluser',
            name='team',
            field=models.CharField(max_length=50),
        ),
    ]
