# Generated by Django 6.0.6 on 2026-07-10 13:21

from django.db import migrations, models


def rename_team_member(apps, schema_editor):
    PortalUser = apps.get_model('users', 'PortalUser')
    PortalUser.objects.filter(user_type='team_member').update(user_type='member')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_team_alter_portaluser_team'),
    ]

    operations = [
        migrations.RunPython(rename_team_member, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='portaluser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
