# Generated by Django 6.0.7 on 2026-07-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_portaluser_team_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaluser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='users.team'),
        ),
    ]
