# Generated by Django 6.0.7 on 2026-07-13 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bearer_token_enc', models.BinaryField()),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, choices=[('ok', 'OK'), ('error', 'Error'), ('token_expired', 'Token Expired')], max_length=20, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enterprises', to='clusters.cluster')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'cluster')},
            },
        ),
    ]
