# Generated by Django 6.0.7 on 2026-07-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0002_portalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='last_sync_error_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
