# Generated by Django 6.0.7 on 2026-07-14 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
        ('device_models', '0001_initial'),
        ('enterprises', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cluster_device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=200, null=True)),
                ('location_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('condition', models.CharField(choices=[('normal', 'Normal'), ('out_of_order', 'Out of Order'), ('needs_repair', 'Needs Repair'), ('temporarily_leased', 'Temporarily Leased'), ('dedicated', 'Dedicated'), ('missing', 'Missing')], default='normal', max_length=20)),
                ('idrac_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('idrac_username', models.CharField(blank=True, max_length=100, null=True)),
                ('idrac_password_enc', models.BinaryField(blank=True, null=True)),
                ('eve_version', models.CharField(blank=True, max_length=200, null=True)),
                ('device_connectivity', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('last_purpose_text', models.TextField(blank=True, null=True)),
                ('last_purpose_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_purpose_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.cluster')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_devices', to='enterprises.enterprise')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device_models.devicemodel')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='users.team')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.lab')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('condition__in', ['normal', 'out_of_order', 'needs_repair', 'temporarily_leased', 'dedicated', 'missing'])), name='device_condition_valid')],
            },
        ),
        migrations.CreateModel(
            name='UntrackedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zcloud_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=400)),
                ('run_state', models.CharField(blank=True, max_length=100)),
                ('eve_version', models.CharField(blank=True, max_length=200, null=True)),
                ('device_connectivity', models.JSONField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='untracked_devices', to='enterprises.enterprise')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'unique_together': {('serial_number', 'enterprise')},
            },
        ),
    ]
