# Generated by Django 6.0.6 on 2026-07-06 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clusters', '0001_initial'),
        ('device_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cluster_device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('team', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=200, null=True)),
                ('lab', models.CharField(choices=[('Bangalore Lab', 'Bangalore Lab'), ('Bangalore Office Space', 'Bangalore Office Space'), ('Berlin Lab', 'Berlin Lab'), ('SanJose Lab', 'SanJose Lab'), ('CoreSite Lab', 'CoreSite Lab'), ('Home Lab', 'Home Lab')], max_length=50)),
                ('location_detail', models.CharField(blank=True, max_length=500, null=True)),
                ('condition', models.CharField(choices=[('normal', 'Normal'), ('out_of_order', 'Out of Order'), ('needs_repair', 'Needs Repair'), ('temporarily_leased', 'Temporarily Leased'), ('dedicated', 'Dedicated')], default='normal', max_length=20)),
                ('idrac_ip', models.CharField(blank=True, max_length=100, null=True)),
                ('idrac_username', models.CharField(blank=True, max_length=100, null=True)),
                ('idrac_password_enc', models.BinaryField(blank=True, null=True)),
                ('eve_version', models.CharField(blank=True, max_length=200, null=True)),
                ('device_connectivity', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('last_comment_text', models.TextField(blank=True, null=True)),
                ('last_comment_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_comment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clusters.cluster')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='device_models.devicemodel')),
            ],
        ),
    ]
