# Generated by Django 6.0.6 on 2026-07-10 07:29

from django.db import migrations, models


_INITIAL_LABS = [
    'Bangalore Lab',
    'Bangalore Office Space',
    'Berlin Lab',
    'CoreSite Lab',
    'Home Lab',
    'SanJose Lab',
]


def seed_labs(apps, schema_editor):
    Lab = apps.get_model('devices', 'Lab')
    for name in _INITIAL_LABS:
        Lab.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_backfill_reserved_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(seed_labs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('normal', 'Normal'), ('out_of_order', 'Out of Order'), ('needs_repair', 'Needs Repair'), ('temporarily_leased', 'Temporarily Leased'), ('dedicated', 'Dedicated'), ('missing', 'Missing')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='lab',
            field=models.CharField(max_length=100),
        ),
    ]
