# Generated by Django 6.0.7 on 2026-07-13 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_rename_comment_fields_to_purpose'),
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_devices', to='enterprises.enterprise'),
        ),
        migrations.CreateModel(
            name='UntrackedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zcloud_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=200)),
                ('model', models.CharField(blank=True, max_length=400)),
                ('run_state', models.CharField(blank=True, max_length=100)),
                ('eve_version', models.CharField(blank=True, max_length=200, null=True)),
                ('device_connectivity', models.JSONField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='untracked_devices', to='enterprises.enterprise')),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'unique_together': {('serial_number', 'enterprise')},
            },
        ),
    ]
